# Generated by Django 2.2.6 on 2019-10-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='filecontent',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='filetype',
            new_name='type',
        ),
    ]
